version: "3.7"
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - .docker.env
    ports:
      - "5432:5432"
    volumes:
      - data_persist:/var/lib/postgresql/data
    networks:
      - network
volumes:
  data_persist:
    driver: local
networks:
  network:
    driver: bridge
